[package]
name = "mauveweasel"
version = "0.1.0"
authors = ["ne0ndrag0n <ne0ndrag0n@users.noreply.github.com>"]

[dependencies]
hyper = "0.12"
toml = "0.4"
bcrypt = "0.2"
serde = "1.0"
serde_derive = "1.0"
